ontents

---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://erica-zhou.github.io/blog"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true
...
